CREATE TABLE customer (
    id BINARY(16) PRIMARY KEY, 
    cpf VARCHAR(15) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT 0, 
    name VARCHAR(255) NOT NULL, 
    birth DATE NOT NULL, 
    password VARCHAR(255) NOT NULL, 
    gender ENUM('MALE', 'WOMAN', 'NOT_INFORMED') NOT NULL,
    ddd VARCHAR(2) NOT NULL, 
    phone VARCHAR(9) NOT NULL,
    type_phone ENUM('MOBILE', 'WHATSAPP', 'FIXED') NOT NULL,
    email VARCHAR(255) NOT NULL 
);
